# Add 'repo' label to any root file changes
repo:
  - ./*

# Add 'core' label to any change within the 'core' package
core:
  - src/*

# Add 'workflow' label to any change within the 'workflow' package
workflow:
  - workflow/*

# Add 'test' label to any change to *.spec.js files within the source dir
test:
  - test/*

S:
  size-below: 10
M:
  size-above: 9
  size-below: 100
L:
  size-above: 100