# Add 'repo' label to any root file changes
repo:
  - ./*

# Add 'core' label to any change within the 'core' package
core:
  - src/*

# Add 'workflow' label to any change within the 'workflow' package
workflow:
  - .github/*
  - .github/workflows/*

# Add 'test' label to any change to *.spec.js files within the source dir
test:
  - test/*
