name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: chrismphilp/react-filter-menu@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
